export const exercises = [
  { name: 'Push-ups', type: 'strength', muscle: 'upper', equipment: 'none' },
  { name: 'Sumo Squats', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Plank', type: 'strength', muscle: 'core', equipment: 'none' },
  { name: 'Pull-ups', type: 'strength', muscle: 'upper', equipment: 'bar' },
  { name: 'Deadlifts', type: 'strength', muscle: 'lower', equipment: 'barbell' },
  { name: 'Russian Twists', type: 'strength', muscle: 'core', equipment: 'medicine ball' },
  { name: 'Bench Press', type: 'strength', muscle: 'upper', equipment: 'barbell' },
  { name: 'Leg Press', type: 'strength', muscle: 'lower', equipment: 'machine' },
  { name: 'Bicycle Crunches', type: 'strength', muscle: 'core', equipment: 'none' },
  { name: 'Overhead Press', type: 'strength', muscle: 'upper', equipment: 'dumbbell' },
  { name: 'Hamstring Curls', type: 'strength', muscle: 'lower', equipment: 'machine' },
  { name: 'Chest Flyes', type: 'strength', muscle: 'upper', equipment: 'cable' },
  { name: 'Glute Bridges', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Leg Raises', type: 'strength', muscle: 'core', equipment: 'none' },
  { name: 'Lat Pulldowns', type: 'strength', muscle: 'upper', equipment: 'machine' },
  { name: 'Calf Raises', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Mountain Climbers', type: 'strength', muscle: 'core', equipment: 'none' },
  { name: 'Dips', type: 'strength', muscle: 'upper', equipment: 'parallel bars' },
  { name: 'Cable Pressdowns', type: 'strength', muscle: 'upper', equipment: 'cable' },
  { name: 'Leg Extensions', type: 'strength', muscle: 'lower', equipment: 'machine' },
  { name: 'Seated Cable Rows', type: 'strength', muscle: 'upper', equipment: 'cable' },
  { name: 'Dumbbell Lateral Raises', type: 'strength', muscle: 'upper', equipment: 'dumbbell' },
  { name: 'Bicep Curls', type: 'strength', muscle: 'upper', equipment: 'dumbbell' },
  { name: 'Tricep Kickbacks', type: 'strength', muscle: 'upper', equipment: 'dumbbell' },
  { name: 'Leg Press', type: 'strength', muscle: 'lower', equipment: 'machine' },
  { name: 'Good Mornings', type: 'strength', muscle: 'lower', equipment: 'barbell' },
  { name: 'Lunges', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Bird Dogs', type: 'strength', muscle: 'core', equipment: 'none' },
  { name: 'Shoulder Shrugs', type: 'strength', muscle: 'upper', equipment: 'dumbbell' },
  { name: 'Crunches', type: 'strength', muscle: 'core', equipment: 'none' },
  { name: 'Back Extensions', type: 'strength', muscle: 'core', equipment: 'machine' },
  { name: 'Wall sits', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Renegade Rows', type: 'strength', muscle: 'upper', equipment: 'dumbbell' },
  { name: 'Fire hydrants', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Superman Hold', type: 'strength', muscle: 'core', equipment: 'none' },
  { name: 'side lying leg lifts', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'adductor machine', type: 'strength', muscle: 'lower', equipment: 'machine' },
  { name: 'abductor machine', type: 'strength', muscle: 'lower', equipment: 'machine' },
  { name: 'Abb wheel rollouts', type: 'strength', muscle: 'core', equipment: 'ab wheel' },
  { name: 'Dumbbell Press', type: 'strength', muscle: 'upper', equipment: 'dumbbell' },
  { name: 'Squats', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Lunges', type: 'strength', muscle: 'lower', equipment: 'none' },
  { name: 'Plank', type: 'strength', muscle: 'core', equipment: 'none' },

  { name: 'Running', type: 'cardio' },
  { name: 'Jump Rope', type: 'cardio' },
  { name: 'Cycling', type: 'cardio' },
  { name: 'Rowing', type: 'cardio' },
    { name: 'Swimming', type: 'cardio' },
    { name: 'Elliptical', type: 'cardio' },
    { name: 'Stair Climber', type: 'cardio' },
    { name: 'High Knees', type: 'cardio' },
    { name: 'Butt Kicks', type: 'cardio' },
    { name: 'Burpees', type: 'cardio' },
    { name: 'Jumping Jacks', type: 'cardio' },
    { name: 'Mountain Climbers', type: 'cardio' },
    { name: 'Sprints', type: 'cardio' },
    { name: 'Box Jumps', type: 'cardio' },
    { name: 'Agility Ladder Drills', type: 'cardio' },
    { name: 'Kettlebell Swings', type: 'cardio' },
    { name: 'Battle Ropes', type: 'cardio' },
    { name: 'Brisk Walking', type: 'cardio' },
    { name: 'Exercise Bike', type: 'cardio' },
    { name: 'Zumba', type: 'cardio' },
    { name: 'Kickboxing', type: 'cardio' },
    { name: 'Pilates', type: 'cardio' },
    { name: 'Yoga', type: 'cardio' },
    { name: 'Hiking', type: 'cardio' },
    { name: 'Dancing', type: 'cardio' },
    { name: 'CrossFit', type: 'cardio' },
    { name: 'Tai Chi', type: 'cardio' },
    { name: 'Tae Kwon Do', type: 'cardio' },
    { name: 'Jump Squats', type: 'cardio' },
    { name: 'Boxing', type: 'cardio' },
    { name: 'Skiing', type: 'cardio' },
   
];
